# Generated by Django 2.2.28 on 2023-05-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='image',
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('blocked', 'Blocked')], max_length=10),
        ),
    ]
