# Generated by Django 2.2.28 on 2023-05-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20230528_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='attend_status',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='status',
        ),
    ]
