# Generated by Django 2.2.28 on 2023-05-31 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20230528_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date (Morocco)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date (Morocco)'),
        ),
    ]
