# Generated by Django 2.2.28 on 2023-05-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20230531_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket',
        ),
    ]
