# Generated by Django 2.2.28 on 2023-05-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket_id',
        ),
    ]
