# Generated by Django 2.2.28 on 2023-05-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20230531_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
