# Generated by Django 2.2.28 on 2023-05-31 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='prix',
            new_name='price',
        ),
    ]
