# Generated by Django 2.2.28 on 2023-05-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20230531_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
