# Generated by Django 2.2.28 on 2023-05-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20230531_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket',
        ),
    ]
