# Generated by Django 2.2.28 on 2023-05-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_event_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
    ]
