# Generated by Django 2.2.28 on 2023-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20230531_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='nbr_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
