# Generated by Django 2.2.28 on 2023-06-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_ticket_nbr_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('Holder', models.CharField(max_length=50)),
                ('eventName', models.CharField(max_length=70)),
                ('paymentDate', models.DateField(auto_now_add=True)),
                ('TicketNumber', models.CharField(max_length=60)),
                ('Quantity', models.IntegerField()),
                ('CardNumber', models.CharField(max_length=20)),
                ('ExperationMonth', models.CharField(max_length=10)),
                ('ExperationYear', models.CharField(max_length=10)),
                ('CVV', models.CharField(max_length=10)),
            ],
        ),
    ]
