# Generated by Django 2.2.28 on 2023-06-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
